name: alphabet_book
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/alphabet_book.png
    - assets/images/orion.png
    - assets/images/a.png
    - assets/images/airplane.png
    - assets/images/b.png
    - assets/images/butterfly.png
    - assets/images/c.png
    - assets/images/car.png
    - assets/images/d.png
    - assets/images/dog.png
    - assets/images/e.png
    - assets/images/elephant.png
    - assets/images/f.png
    - assets/images/flower.png
    - assets/images/g.png
    - assets/images/grasshopper.png
    - assets/images/h.png
    - assets/images/helicopter.png
    - assets/images/i.png
    - assets/images/icecream.png
    - assets/images/j.png
    - assets/images/jellyfish.png
    - assets/images/k.png
    - assets/images/key.png
    - assets/images/l.png
    - assets/images/lion.png
    - assets/images/m.png
    - assets/images/monkey.png
    - assets/images/n.png
    - assets/images/noodles.png
    - assets/images/o.png
    - assets/images/owl.png
    - assets/images/p.png
    - assets/images/panda.png
    - assets/images/q.png
    - assets/images/quokka.png
    - assets/images/r.png
    - assets/images/robot.png
    - assets/images/s.png
    - assets/images/star.png
    - assets/images/t.png
    - assets/images/tiger.png
    - assets/images/u.png
    - assets/images/umbrella.png
    - assets/images/v.png
    - assets/images/vase.png
    - assets/images/w.png
    - assets/images/watermelon.png
    - assets/images/x.png
    - assets/images/xylophone.png
    - assets/images/y.png
    - assets/images/yacht.png
    - assets/images/z.png
    - assets/images/zebra.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
